theme: 
  - osuny
  - osuny-plugin-centered-footer
_merge: deep
params:
  additional_csp: 'use.typekit.net p.typekit.net'
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-white.svg'
  home:
    head:
      title: site
  menu:
    primary:
      level_1:
        dropdown: true
        summary:
          active: false
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
      level_2:
        dropdown: false
        summary:
          active: true
          source: "Summary" # "Summary" | "meta_description"
          truncate: 0
        title:
          active: false
          summary:
            active: false
            source: "Summary" # "Summary" | "meta_description"
            truncate: 125
      level_3:
        dropdown: false
        summary:
          active: false
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  projects:
    default_image: true
    index:
      options:
        categories: false
    single:
      options:
        reading_time: false
