[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/references/concours-d-operateurs-immobiliers/index.html"
to = "/references/domaines/immobilier-et-equipements/concours-d-operateurs-immobiliers/"

[[redirects]]
from = "/references/amu/index.html"
to = "/references/missions/amu/"

[[redirects]]
from = "/references/concertation/index.html"
to = "/references/missions/concertation/"

[[redirects]]
from = "/references/urbanisme-transitoire/index.html"
to = "/references/missions/urbanisme-transitoire/"

[[redirects]]
from = "/projets/index.html"
to = "/references/"

[[redirects]]
from = "/notre-raison-detre/index.html"
to = "/lagence/notre-raison-detre/"

[[redirects]]
from = "/services/index.html"
to = "/lagence/services/"

[[redirects]]
from = "/references/intelligence-collective/index.html"
to = "/references/missions/intelligence-collective/"

[[redirects]]
from = "/references/urbanisme-et-logement/index.html"
to = "/references/domaines/politiques-publiques/urbanisme-et-logement/"

[[redirects]]
from = "/references/equipements-publics/index.html"
to = "/references/domaines/immobilier-et-equipements/equipements-publics/"

[[redirects]]
from = "/references/assistance-a-maitrise-d-usage/index.html"
to = "/references/missions/urbanisme-transitoire/"

